name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
      - name: Install Rocq
        uses: tchajed/setup-rocq@v1
      - name: Install dependencies
        run: |
          opam pin add --no-action .
          opam install --deps-only .
      - name: Rocq build
        run: dune build
      - name: opam install
        run: opam install --assume-built .
      - name: opam uninstall
        run: opam uninstall .

  check-goose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
      - name: check goose output
        run: |
          git clone --depth=1 https://github.com/mit-pdos/go-journal ~/go-journal
          git clone --depth=1 https://github.com/mit-pdos/go-nfsd ~/go-nfsd
          ./etc/update-goose.sh --go-journal ~/go-journal --go-nfsd ~/go-nfsd
          git diff --exit-code
